var fullDeck = [
  {name:'assets/blue-01.png', number:1, color:'blue'},
  {name:'assets/blue-02.png', number:2, color:'blue'},
  {name:'assets/blue-03.png', number:3, color:'blue'},
  {name:'assets/blue-04.png', number:4, color:'blue'},
  {name:'assets/blue-05.png', number:5, color:'blue'},
  {name:'assets/blue-06.png', number:6, color:'blue'},
  {name:'assets/blue-07.png', number:7, color:'blue'},
  {name:'assets/blue-08.png', number:8, color:'blue'},
  {name:'assets/blue-09.png', number:9, color:'blue'},
  {name:'assets/blue-10.png', number:10, color:'blue'},
  {name:'assets/blue-jack.png', number:'jack', color:'blue'},
  {name:'assets/blue-king.png', number:'king', color:'blue'},
  {name:'assets/blue-queen.png', number:'queen', color:'blue'},
  {name:'assets/gold-01.png', number:1, color:'gold'},
  {name:'assets/gold-02.png', number:2, color:'gold'},
  {name:'assets/gold-03.png', number:3, color:'gold'},
  {name:'assets/gold-04.png', number:4, color:'gold'},
  {name:'assets/gold-05.png', number:5, color:'gold'},
  {name:'assets/gold-06.png', number:6, color:'gold'},
  {name:'assets/gold-07.png', number:7, color:'gold'},
  {name:'assets/gold-08.png', number:8, color:'gold'},
  {name:'assets/gold-09.png', number:9, color:'gold'},
  {name:'assets/gold-10.png', number:10, color:'gold'},
  {name:'assets/gold-jack.png', number:'jack', color:'gold'},
  {name:'assets/gold-king.png', number:'king', color:'gold'},
  {name:'assets/gold-queen.png', number:'queen', color:'gold'},
  {name:'assets/green-01.png', number:1, color:'green'},
  {name:'assets/green-02.png', number:2, color:'green'},
  {name:'assets/green-03.png', number:3, color:'green'},
  {name:'assets/green-04.png', number:4, color:'green'},
  {name:'assets/green-05.png', number:5, color:'green'},
  {name:'assets/green-06.png', number:6, color:'green'},
  {name:'assets/green-07.png', number:7, color:'green'},
  {name:'assets/green-08.png', number:8, color:'green'},
  {name:'assets/green-09.png', number:9, color:'green'},
  {name:'assets/green-10.png', number:10, color:'green'},
  {name:'assets/green-jack.png', number:'jack', color:'green'},
  {name:'assets/green-king.png', number:'king', color:'green'},
  {name:'assets/green-queen.png', number:'queen', color:'green'},
  {name:'assets/red-01.png', number:1, color:'red'},
  {name:'assets/red-02.png', number:2, color:'red'},
  {name:'assets/red-03.png', number:3, color:'red'},
  {name:'assets/red-04.png', number:4, color:'red'},
  {name:'assets/red-05.png', number:5, color:'red'},
  {name:'assets/red-06.png', number:6, color:'red'},
  {name:'assets/red-07.png', number:7, color:'red'},
  {name:'assets/red-08.png', number:8, color:'red'},
  {name:'assets/red-09.png', number:9, color:'red'},
  {name:'assets/red-10.png', number:10, color:'red'},
  {name:'assets/red-jack.png', number:'jack', color:'red'},
  {name:'assets/red-king.png', number:'king', color:'red'},
  {name:'assets/red-queen.png', number:'queen', color:'red'}
]

var player1Cards = fullDeck.slice(0,26);
var player2Cards = fullDeck.slice(26);